### ISSUE TITLE
Readme is showing insted of the website while hosting in githubj

### ISSUE THREAD

**Issue by haroonalbar** [developedbyed/react-portofolio-with-tailwind#4]
any solutions?

**Comment by GVishnudhasan** [comment]
Github gives you multiple choices of where it takes its sources from. By default, it's the root of the master branch, which will use `README.md` in case there is no `index.html`.

But you can also switch to the docs/ folder in your repository settings. You can put the `index.html` under the `docs/ folder`.

Otherwise, Consider moving your web content into the root of your repository and renaming your default page to `index.md` or `index.html`, depending on the type of file. (By convention the default page of most websites is called `index.html`, and this is what GitHub Pages will show by default if it exists.)
